name: Erlang CI

on: [release]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: rebar3 get-deps
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 eunit
